# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTBiZjVmYjY0ZWJmYWU0YzExZWNmMDYwOTRmM2E1MTg3M2U2NTg3ZWI4OTZiMzdiMTFjZmQ2NDFjYTQ1ODdmZjQyNDZhMWFjMGI2ZjNkMzBhMTkzYmMxZTFlMjRhN2Y0NDIxNDJkMjdlYTNlYzRlMDljMzZlNzNjZDU1OTdlNjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
